"""Add Rule model

Revision ID: 04adfdc869ca
Revises: 8dfbc96fe38c
Create Date: 2026-03-18 23:05:17.596848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04adfdc869ca'
down_revision: Union[str, Sequence[str], None] = '8dfbc96fe38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('amount_sign', sa.String(), nullable=True),
    sa.Column('amount_min', sa.Float(), nullable=True),
    sa.Column('amount_max', sa.Float(), nullable=True),
    sa.Column('account_filter', sa.String(), nullable=True),
    sa.Column('category_filter', sa.String(), nullable=True),
    sa.Column('assign_payee', sa.String(), nullable=True),
    sa.Column('assign_category', sa.String(), nullable=True),
    sa.Column('flag_review', sa.Boolean(), nullable=True),
    sa.Column('flag_ignore', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    # ### end Alembic commands ###
