"""Add per-entity knowledge fields to plans

Revision ID: 211df7b030a2
Revises: 04adfdc869ca
Create Date: 2026-03-20 10:30:29.485459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211df7b030a2'
down_revision: Union[str, Sequence[str], None] = '04adfdc869ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('last_knowledge_payees', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('last_knowledge_transactions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'last_knowledge_transactions')
    op.drop_column('plans', 'last_knowledge_payees')
    # ### end Alembic commands ###
