"""add transfer_account_id to payees

Revision ID: 68a8c6c9c098
Revises: a3b1c2d4e5f6
Create Date: 2026-03-24 23:26:05.656541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a8c6c9c098'
down_revision: Union[str, Sequence[str], None] = 'a3b1c2d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payees', sa.Column('transfer_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payees', 'transfer_account_id')
    # ### end Alembic commands ###
